name: Deploy to GitHub Pages

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: prod
          path: 'italian-frequency-ui'

      - name: Install dependencies
        run: |
          cd italian-frequency-ui
          npm install

      - name: Build the app
        run: |
          cd italian-frequency-ui
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./italian-frequency-ui/dist
          commit_message: Deploy from GitHub Actions
          commit_user_name: Charlotte Kies
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
