name: Deploy to GitHub Pages
on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: ./italian-frequency-ui

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        working-directory: italian-frequency-ui
        run: |
          cd italian-frequency-ui
          npm ci

      - name: Build and deploy
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        working-directory: italian-frequency-ui
        run: |
          cd italian-frequency-ui
          npm run build
          sed -i "s|process.env.API_BASE_URL|'${{ secrets.API_BASE_URL }}'|g" dist/js/app.*.js
          ls

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: italian-frequency-ui/dist
