name: Deploy to GitHub Pages
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          ref: prod
          path: italian-frequency-ui
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        working-directory: italian-frequency-ui
        run: npm install
        
      - name: Build and deploy
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          npm run build
          sed -i "s|process.env.API_BASE_URL|'${API_BASE_URL}'|g" italian-frequency-ui/dist/js/app.*.js
          npx gh-pages -d italian-frequency-ui -b gh-pages -u ${{ github.actor }}
        working-directory: italian-words-by-frequency-ui
