name: Deploy to GitHub Pages

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Build and Deploy
        run: |
          cd frontend
          npm run build
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env.production
          npm install -g push-dir
          push-dir --dir=dist --branch=gh-pages --cleanup
