steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/checkout@v3

  # Sets up Node.js 16.x
  - name: Setup Node.js 16.x
    uses: actions/setup-node@v3
    with:
      node-version: "16.x"

  # Installs dependencies
  - name: Install dependencies
    run: npm install

  # Builds the Vue.js project
  - name: Build Vue.js project
    run: npm run build

  # Deploy to GitHub Pages
  - name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@4.1.4
    with:
      branch: gh-pages
      folder: dist
      clean: true
    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
